server {
    listen 3000;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # TODO (Fase 2): configure el "fallback" de Single Page Application.
        # TODO: complete la directiva aquí.
    }

    # Opcional: cache agresiva para assets con hash de contenido (Vite).
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
