version: "3.9"

services:
  nexus:
    image: sonatype/nexus3:3.68.1
    container_name: nexus
    networks:
      - cicd_network
    ports:
      - "${NEXUS_UI_PORT}:8081"
      - "${NEXUS_DOCKER_REGISTRY_PORT}:8082"
    volumes:
      - nexus_data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx1200m -XX:MaxDirectMemorySize=2g
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/service/rest/v1/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  cicd_network:
    external: true

volumes:
  nexus_data: